providers:
  default: ollama
  ollama:
    provider: Ollama
    model: "llama3.1"
    config:
      host: host.docker.internal:11434

# Add a dummy OpenAI API key for the tools-server
# openAI:
#   apiKey: "dummy-value-for-tools-server"

k8s-agent:
  enabled: true

kgateway-agent:
  enabled: true

istio-agent:
  enabled: false

promql-agent:
  enabled: true

observability-agent:
  enabled: true

argo-rollouts-agent:
  enabled: false

helm-agent:
  enabled: false

cilium-policy-agent:
  enabled: false

cilium-manager-agent:
  enabled: false

cilium-debug-agent:
  enabled: false